version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=secretsmanager # Write the AWS services you want to use, separated by commas
      - DEBUG=${DEBUG:-0}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
